-- UC12: Architecture Decision Assistant — SQL Validation

-- 1. Confirm ADRs loaded
SELECT COUNT(*) AS TOTAL_ADRS
FROM AI_DEMO.ARCHITECTURE_DECISIONS;

-- 2. List all ADRs with status
SELECT DOCUMENT_ID, TITLE, STATUS, EFFECTIVE_DATE
FROM AI_DEMO.ARCHITECTURE_DECISIONS
ORDER BY DOCUMENT_ID;

-- 3. ADRs by status
SELECT STATUS, COUNT(*) AS COUNT
FROM AI_DEMO.ARCHITECTURE_DECISIONS
GROUP BY STATUS;

-- 4. Verify embeddings are stored
SELECT DOCUMENT_ID, LENGTH(EMBEDDING) AS EMBEDDING_BYTES
FROM AI_DEMO.ARCHITECTURE_DECISIONS
WHERE EMBEDDING IS NOT NULL
ORDER BY DOCUMENT_ID;

-- 5. ADRs available for semantic search (ACCEPTED or ACTIVE only)
SELECT DOCUMENT_ID, TITLE
FROM AI_DEMO.ARCHITECTURE_DECISIONS
WHERE STATUS IN ('ACTIVE', 'ACCEPTED')
ORDER BY DOCUMENT_ID;
