-- UC02: Policy Assistant with Metadata Filtering — SQL Validation

-- 1. Count active Europe Finance policies
SELECT COUNT(*) AS ACTIVE_EUROPE_FINANCE_POLICIES
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'policy'
  AND DEPARTMENT = 'Finance'
  AND REGION = 'EUROPE'
  AND STATUS = 'ACTIVE';

-- 2. Metadata distribution across all policies
SELECT DEPARTMENT, REGION, STATUS, COUNT(*) AS DOC_COUNT
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'policy'
GROUP BY DEPARTMENT, REGION, STATUS
ORDER BY DOC_COUNT DESC;

-- 3. List all active policies with effective dates
SELECT DOCUMENT_ID, TITLE, DEPARTMENT, REGION, EFFECTIVE_DATE, STATUS
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'policy'
  AND STATUS = 'ACTIVE'
ORDER BY EFFECTIVE_DATE DESC;

-- 4. Verify compound filter would return correct result
SELECT DOCUMENT_ID, TITLE
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'policy'
  AND DEPARTMENT = 'Finance'
  AND REGION = 'EUROPE'
  AND STATUS = 'ACTIVE'
  AND EFFECTIVE_DATE <= CURRENT DATE;
-- Expected: POL-001 only
