-- UC11: Vector-Based Incident Discovery — SQL Validation

-- 1. Confirm incidents table is populated
SELECT COUNT(*) AS TOTAL_INCIDENTS
FROM AI_DEMO.INCIDENTS;

-- 2. Review incident metadata
SELECT DOCUMENT_ID, TITLE,
       SUBSTR(CONTENT, 1, 100) AS CONTENT_PREVIEW,
       EFFECTIVE_DATE
FROM AI_DEMO.INCIDENTS
ORDER BY EFFECTIVE_DATE DESC;

-- 3. Severity distribution
SELECT CLASSIFICATION AS SEVERITY_TAG, COUNT(*) AS COUNT
FROM AI_DEMO.INCIDENTS
GROUP BY CLASSIFICATION;

-- 4. Incidents by department (service domain)
SELECT DEPARTMENT, PRODUCT, COUNT(*) AS COUNT
FROM AI_DEMO.INCIDENTS
GROUP BY DEPARTMENT, PRODUCT
ORDER BY COUNT DESC;

-- 5. Confirm embeddings for all incidents
SELECT COUNT(*) AS INCIDENTS_WITH_EMBEDDING
FROM AI_DEMO.INCIDENTS
WHERE EMBEDDING IS NOT NULL;
