-- UC17: Semantic Ticket Routing — SQL Validation

-- 1. Confirm ticket history table is populated
SELECT COUNT(*) AS TOTAL_TICKETS
FROM AI_DEMO.TICKETS;

-- 2. Team distribution in historical tickets (routing targets)
SELECT DEPARTMENT AS TEAM, COUNT(*) AS TICKET_COUNT
FROM AI_DEMO.TICKETS
GROUP BY DEPARTMENT
ORDER BY TICKET_COUNT DESC;

-- 3. Category distribution
SELECT DOCUMENT_TYPE AS CATEGORY, COUNT(*) AS COUNT
FROM AI_DEMO.TICKETS
GROUP BY DOCUMENT_TYPE
ORDER BY COUNT DESC;

-- 4. Sample ticket metadata
SELECT DOCUMENT_ID, TITLE, DEPARTMENT AS TEAM,
       SUBSTR(CONTENT, 1, 100) AS SYMPTOM_PREVIEW
FROM AI_DEMO.TICKETS
FETCH FIRST 10 ROWS ONLY;

-- 5. Verify embeddings stored for all tickets
SELECT COUNT(*) AS TICKETS_WITH_EMBEDDING
FROM AI_DEMO.TICKETS
WHERE EMBEDDING IS NOT NULL;
