-- UC03: Technical Documentation Semantic Search — SQL Validation

-- 1. Count technical documents
SELECT COUNT(*) AS TOTAL_TECHNICAL_DOCS
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'technical';

-- 2. List all technical documents with metadata
SELECT DOCUMENT_ID, TITLE, DEPARTMENT, PRODUCT, STATUS, EFFECTIVE_DATE
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'technical'
ORDER BY EFFECTIVE_DATE DESC;

-- 3. Confirm embeddings exist for all technical docs
SELECT COUNT(*) AS DOCS_WITH_EMBEDDING
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'technical'
  AND EMBEDDING IS NOT NULL;

-- 4. Sample content snippets
SELECT DOCUMENT_ID, TITLE,
       SUBSTR(CONTENT, 1, 150) AS CONTENT_SNIPPET
FROM AI_DEMO.KNOWLEDGE_BASE
WHERE DOCUMENT_TYPE = 'technical'
ORDER BY DOCUMENT_ID;
